# Generated by Django 6.0.6 on 2026-06-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(help_text="URL-friendly version of the title (e.g., 'epic-gaming-news')", unique=True)),
                ('content', models.TextField(help_text='Write your main blog article here.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube embed link here if the post has a video.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
